# instruct GitHub dependabot to scan github actions for updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
        # group all run-of-the mill updates into a single pull request
    groups:
      gha-updates:
        applies-to: version-updates
        update-types:
          - patch
          - minor

  - package-ecosystem: "pip"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
    # group all run-of-the mill updates into a single pull request
    groups:
      py-updates:
        applies-to: version-updates
